### ISSUE TITLE
Include a JSON mapping from english names to latin names for breeding birds to be able to show the vulnerability

### ISSUE THREAD

**Issue by George-Ogden** [btovis/btovis.github.io#176]

**Comment by CGDogan** [comment]
Is it for bird csvs? before I saw this issue I had made some work into the bird branch

**Comment by CGDogan** [comment]
Actually I'll open this as a pull request and as you'll see the bird names are broken because for the species code and the english name to occupy the correct places in the UI, I renamed columns, but I renamed them poorly so you can fix it or remove that and replace with any alternative you would like but I need to push because my CSV parser, as with all my code, had a bug

**Comment by George-Ogden** [comment]
It's so that if you look up the species or English name of a bird that does not exist, you get a response that is unkown

**Comment by CGDogan** [comment]
As of now, yes:

![Screenshot 2024-02-28 at 17 09 36](https://github.com/btovis/btovis.github.io/assets/126820728/dde4fa27-7d43-4dd8-947c-62634306ef58)

It's looking up with an english name for a latin name database

**Comment by CGDogan** [comment]
A systematic approach could be parsing the list on the website, then filtering it by latin names existing in our extinction database.

**Comment by CGDogan** [comment]
Are we sure about closing this? It might be useful to see vulnerability status of birds
