### ISSUE TITLE
fix why some columns being chosen break table

### ISSUE THREAD

**Issue by CGDogan** [btovis/btovis.github.io#207]

**Comment by Hex27** [comment]
In my own investigation, its because of keyFromRow inside the table widget. That method constructs a unique key that can be used for indexing by the search bar, but it becomes terrible as the key becomes long (i.e. concatinating many many columns)

Additionally, cases which try to get nearly as many rows as the original csv (i.e. filter by only probability) tend to cause issues too (i.e. rows like probability or recording file name)

I'm speculating that the search bar is causing this, because it was much faster when I stopped using it, but it's also a very important feature for it

**Comment by Hex27** [comment]
#214
