### ISSUE TITLE
Widget options

### ISSUE THREAD

**Issue by cshuenss** [btovis/btovis.github.io#70]
Need to be able to change settings for widgets

**Comment by SatoruQ** [comment]
Current plan: since there's almost no render options field shared by all plotly widgets, we do not use the WidgetConfig class for widget options. Instead, hard code every option as another InputOption so it also suits the sidebar better. 

- [ ] Line Chart Options
- [ ] Bar Chart Options
- [ ] Stacked Line Chart Options
- [ ] Map Options

**Comment by SatoruQ** [comment]
Adding another few classes extending Input Option.
